//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AreaYPerimetro.perimetro1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="perimetro1.PerimetrosSoap")]
    public interface PerimetrosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento PerimetroTrianguloResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PerimetroTriangulo", ReplyAction="*")]
        AreaYPerimetro.perimetro1.PerimetroTrianguloResponse PerimetroTriangulo(AreaYPerimetro.perimetro1.PerimetroTrianguloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PerimetroTriangulo", ReplyAction="*")]
        System.Threading.Tasks.Task<AreaYPerimetro.perimetro1.PerimetroTrianguloResponse> PerimetroTrianguloAsync(AreaYPerimetro.perimetro1.PerimetroTrianguloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento PerimetroCuadrdoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PerimetroCuadrdo", ReplyAction="*")]
        AreaYPerimetro.perimetro1.PerimetroCuadrdoResponse PerimetroCuadrdo(AreaYPerimetro.perimetro1.PerimetroCuadrdoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PerimetroCuadrdo", ReplyAction="*")]
        System.Threading.Tasks.Task<AreaYPerimetro.perimetro1.PerimetroCuadrdoResponse> PerimetroCuadrdoAsync(AreaYPerimetro.perimetro1.PerimetroCuadrdoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento PerimetroCirculoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PerimetroCirculo", ReplyAction="*")]
        AreaYPerimetro.perimetro1.PerimetroCirculoResponse PerimetroCirculo(AreaYPerimetro.perimetro1.PerimetroCirculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PerimetroCirculo", ReplyAction="*")]
        System.Threading.Tasks.Task<AreaYPerimetro.perimetro1.PerimetroCirculoResponse> PerimetroCirculoAsync(AreaYPerimetro.perimetro1.PerimetroCirculoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PerimetroTrianguloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PerimetroTriangulo", Namespace="http://tempuri.org/", Order=0)]
        public AreaYPerimetro.perimetro1.PerimetroTrianguloRequestBody Body;
        
        public PerimetroTrianguloRequest() {
        }
        
        public PerimetroTrianguloRequest(AreaYPerimetro.perimetro1.PerimetroTrianguloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PerimetroTrianguloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double lado;
        
        public PerimetroTrianguloRequestBody() {
        }
        
        public PerimetroTrianguloRequestBody(double lado) {
            this.lado = lado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PerimetroTrianguloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PerimetroTrianguloResponse", Namespace="http://tempuri.org/", Order=0)]
        public AreaYPerimetro.perimetro1.PerimetroTrianguloResponseBody Body;
        
        public PerimetroTrianguloResponse() {
        }
        
        public PerimetroTrianguloResponse(AreaYPerimetro.perimetro1.PerimetroTrianguloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PerimetroTrianguloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PerimetroTrianguloResult;
        
        public PerimetroTrianguloResponseBody() {
        }
        
        public PerimetroTrianguloResponseBody(string PerimetroTrianguloResult) {
            this.PerimetroTrianguloResult = PerimetroTrianguloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PerimetroCuadrdoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PerimetroCuadrdo", Namespace="http://tempuri.org/", Order=0)]
        public AreaYPerimetro.perimetro1.PerimetroCuadrdoRequestBody Body;
        
        public PerimetroCuadrdoRequest() {
        }
        
        public PerimetroCuadrdoRequest(AreaYPerimetro.perimetro1.PerimetroCuadrdoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PerimetroCuadrdoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double lado1;
        
        public PerimetroCuadrdoRequestBody() {
        }
        
        public PerimetroCuadrdoRequestBody(double lado1) {
            this.lado1 = lado1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PerimetroCuadrdoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PerimetroCuadrdoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AreaYPerimetro.perimetro1.PerimetroCuadrdoResponseBody Body;
        
        public PerimetroCuadrdoResponse() {
        }
        
        public PerimetroCuadrdoResponse(AreaYPerimetro.perimetro1.PerimetroCuadrdoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PerimetroCuadrdoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PerimetroCuadrdoResult;
        
        public PerimetroCuadrdoResponseBody() {
        }
        
        public PerimetroCuadrdoResponseBody(string PerimetroCuadrdoResult) {
            this.PerimetroCuadrdoResult = PerimetroCuadrdoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PerimetroCirculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PerimetroCirculo", Namespace="http://tempuri.org/", Order=0)]
        public AreaYPerimetro.perimetro1.PerimetroCirculoRequestBody Body;
        
        public PerimetroCirculoRequest() {
        }
        
        public PerimetroCirculoRequest(AreaYPerimetro.perimetro1.PerimetroCirculoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PerimetroCirculoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double radio;
        
        public PerimetroCirculoRequestBody() {
        }
        
        public PerimetroCirculoRequestBody(double radio) {
            this.radio = radio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PerimetroCirculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PerimetroCirculoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AreaYPerimetro.perimetro1.PerimetroCirculoResponseBody Body;
        
        public PerimetroCirculoResponse() {
        }
        
        public PerimetroCirculoResponse(AreaYPerimetro.perimetro1.PerimetroCirculoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PerimetroCirculoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PerimetroCirculoResult;
        
        public PerimetroCirculoResponseBody() {
        }
        
        public PerimetroCirculoResponseBody(string PerimetroCirculoResult) {
            this.PerimetroCirculoResult = PerimetroCirculoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PerimetrosSoapChannel : AreaYPerimetro.perimetro1.PerimetrosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PerimetrosSoapClient : System.ServiceModel.ClientBase<AreaYPerimetro.perimetro1.PerimetrosSoap>, AreaYPerimetro.perimetro1.PerimetrosSoap {
        
        public PerimetrosSoapClient() {
        }
        
        public PerimetrosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PerimetrosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerimetrosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerimetrosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AreaYPerimetro.perimetro1.PerimetroTrianguloResponse AreaYPerimetro.perimetro1.PerimetrosSoap.PerimetroTriangulo(AreaYPerimetro.perimetro1.PerimetroTrianguloRequest request) {
            return base.Channel.PerimetroTriangulo(request);
        }
        
        public string PerimetroTriangulo(double lado) {
            AreaYPerimetro.perimetro1.PerimetroTrianguloRequest inValue = new AreaYPerimetro.perimetro1.PerimetroTrianguloRequest();
            inValue.Body = new AreaYPerimetro.perimetro1.PerimetroTrianguloRequestBody();
            inValue.Body.lado = lado;
            AreaYPerimetro.perimetro1.PerimetroTrianguloResponse retVal = ((AreaYPerimetro.perimetro1.PerimetrosSoap)(this)).PerimetroTriangulo(inValue);
            return retVal.Body.PerimetroTrianguloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AreaYPerimetro.perimetro1.PerimetroTrianguloResponse> AreaYPerimetro.perimetro1.PerimetrosSoap.PerimetroTrianguloAsync(AreaYPerimetro.perimetro1.PerimetroTrianguloRequest request) {
            return base.Channel.PerimetroTrianguloAsync(request);
        }
        
        public System.Threading.Tasks.Task<AreaYPerimetro.perimetro1.PerimetroTrianguloResponse> PerimetroTrianguloAsync(double lado) {
            AreaYPerimetro.perimetro1.PerimetroTrianguloRequest inValue = new AreaYPerimetro.perimetro1.PerimetroTrianguloRequest();
            inValue.Body = new AreaYPerimetro.perimetro1.PerimetroTrianguloRequestBody();
            inValue.Body.lado = lado;
            return ((AreaYPerimetro.perimetro1.PerimetrosSoap)(this)).PerimetroTrianguloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AreaYPerimetro.perimetro1.PerimetroCuadrdoResponse AreaYPerimetro.perimetro1.PerimetrosSoap.PerimetroCuadrdo(AreaYPerimetro.perimetro1.PerimetroCuadrdoRequest request) {
            return base.Channel.PerimetroCuadrdo(request);
        }
        
        public string PerimetroCuadrdo(double lado1) {
            AreaYPerimetro.perimetro1.PerimetroCuadrdoRequest inValue = new AreaYPerimetro.perimetro1.PerimetroCuadrdoRequest();
            inValue.Body = new AreaYPerimetro.perimetro1.PerimetroCuadrdoRequestBody();
            inValue.Body.lado1 = lado1;
            AreaYPerimetro.perimetro1.PerimetroCuadrdoResponse retVal = ((AreaYPerimetro.perimetro1.PerimetrosSoap)(this)).PerimetroCuadrdo(inValue);
            return retVal.Body.PerimetroCuadrdoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AreaYPerimetro.perimetro1.PerimetroCuadrdoResponse> AreaYPerimetro.perimetro1.PerimetrosSoap.PerimetroCuadrdoAsync(AreaYPerimetro.perimetro1.PerimetroCuadrdoRequest request) {
            return base.Channel.PerimetroCuadrdoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AreaYPerimetro.perimetro1.PerimetroCuadrdoResponse> PerimetroCuadrdoAsync(double lado1) {
            AreaYPerimetro.perimetro1.PerimetroCuadrdoRequest inValue = new AreaYPerimetro.perimetro1.PerimetroCuadrdoRequest();
            inValue.Body = new AreaYPerimetro.perimetro1.PerimetroCuadrdoRequestBody();
            inValue.Body.lado1 = lado1;
            return ((AreaYPerimetro.perimetro1.PerimetrosSoap)(this)).PerimetroCuadrdoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AreaYPerimetro.perimetro1.PerimetroCirculoResponse AreaYPerimetro.perimetro1.PerimetrosSoap.PerimetroCirculo(AreaYPerimetro.perimetro1.PerimetroCirculoRequest request) {
            return base.Channel.PerimetroCirculo(request);
        }
        
        public string PerimetroCirculo(double radio) {
            AreaYPerimetro.perimetro1.PerimetroCirculoRequest inValue = new AreaYPerimetro.perimetro1.PerimetroCirculoRequest();
            inValue.Body = new AreaYPerimetro.perimetro1.PerimetroCirculoRequestBody();
            inValue.Body.radio = radio;
            AreaYPerimetro.perimetro1.PerimetroCirculoResponse retVal = ((AreaYPerimetro.perimetro1.PerimetrosSoap)(this)).PerimetroCirculo(inValue);
            return retVal.Body.PerimetroCirculoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AreaYPerimetro.perimetro1.PerimetroCirculoResponse> AreaYPerimetro.perimetro1.PerimetrosSoap.PerimetroCirculoAsync(AreaYPerimetro.perimetro1.PerimetroCirculoRequest request) {
            return base.Channel.PerimetroCirculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AreaYPerimetro.perimetro1.PerimetroCirculoResponse> PerimetroCirculoAsync(double radio) {
            AreaYPerimetro.perimetro1.PerimetroCirculoRequest inValue = new AreaYPerimetro.perimetro1.PerimetroCirculoRequest();
            inValue.Body = new AreaYPerimetro.perimetro1.PerimetroCirculoRequestBody();
            inValue.Body.radio = radio;
            return ((AreaYPerimetro.perimetro1.PerimetrosSoap)(this)).PerimetroCirculoAsync(inValue);
        }
    }
}
