//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AreaYPerimetro.area1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="area1.AreasPerimetrosSoap")]
    public interface AreasPerimetrosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento AreaTrianguloResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        AreaYPerimetro.area1.AreaTrianguloResponse AreaTriangulo(AreaYPerimetro.area1.AreaTrianguloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        System.Threading.Tasks.Task<AreaYPerimetro.area1.AreaTrianguloResponse> AreaTrianguloAsync(AreaYPerimetro.area1.AreaTrianguloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento AreaCuadradoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        AreaYPerimetro.area1.AreaCuadradoResponse AreaCuadrado(AreaYPerimetro.area1.AreaCuadradoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        System.Threading.Tasks.Task<AreaYPerimetro.area1.AreaCuadradoResponse> AreaCuadradoAsync(AreaYPerimetro.area1.AreaCuadradoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento AreaCirculoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        AreaYPerimetro.area1.AreaCirculoResponse AreaCirculo(AreaYPerimetro.area1.AreaCirculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        System.Threading.Tasks.Task<AreaYPerimetro.area1.AreaCirculoResponse> AreaCirculoAsync(AreaYPerimetro.area1.AreaCirculoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaTrianguloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AreaTriangulo", Namespace="http://tempuri.org/", Order=0)]
        public AreaYPerimetro.area1.AreaTrianguloRequestBody Body;
        
        public AreaTrianguloRequest() {
        }
        
        public AreaTrianguloRequest(AreaYPerimetro.area1.AreaTrianguloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AreaTrianguloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double altura;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double base1;
        
        public AreaTrianguloRequestBody() {
        }
        
        public AreaTrianguloRequestBody(double altura, double base1) {
            this.altura = altura;
            this.base1 = base1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaTrianguloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AreaTrianguloResponse", Namespace="http://tempuri.org/", Order=0)]
        public AreaYPerimetro.area1.AreaTrianguloResponseBody Body;
        
        public AreaTrianguloResponse() {
        }
        
        public AreaTrianguloResponse(AreaYPerimetro.area1.AreaTrianguloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AreaTrianguloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AreaTrianguloResult;
        
        public AreaTrianguloResponseBody() {
        }
        
        public AreaTrianguloResponseBody(string AreaTrianguloResult) {
            this.AreaTrianguloResult = AreaTrianguloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaCuadradoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AreaCuadrado", Namespace="http://tempuri.org/", Order=0)]
        public AreaYPerimetro.area1.AreaCuadradoRequestBody Body;
        
        public AreaCuadradoRequest() {
        }
        
        public AreaCuadradoRequest(AreaYPerimetro.area1.AreaCuadradoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AreaCuadradoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double lado1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double lado2;
        
        public AreaCuadradoRequestBody() {
        }
        
        public AreaCuadradoRequestBody(double lado1, double lado2) {
            this.lado1 = lado1;
            this.lado2 = lado2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaCuadradoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AreaCuadradoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AreaYPerimetro.area1.AreaCuadradoResponseBody Body;
        
        public AreaCuadradoResponse() {
        }
        
        public AreaCuadradoResponse(AreaYPerimetro.area1.AreaCuadradoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AreaCuadradoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AreaCuadradoResult;
        
        public AreaCuadradoResponseBody() {
        }
        
        public AreaCuadradoResponseBody(string AreaCuadradoResult) {
            this.AreaCuadradoResult = AreaCuadradoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaCirculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AreaCirculo", Namespace="http://tempuri.org/", Order=0)]
        public AreaYPerimetro.area1.AreaCirculoRequestBody Body;
        
        public AreaCirculoRequest() {
        }
        
        public AreaCirculoRequest(AreaYPerimetro.area1.AreaCirculoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AreaCirculoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double radio1;
        
        public AreaCirculoRequestBody() {
        }
        
        public AreaCirculoRequestBody(double radio1) {
            this.radio1 = radio1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaCirculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AreaCirculoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AreaYPerimetro.area1.AreaCirculoResponseBody Body;
        
        public AreaCirculoResponse() {
        }
        
        public AreaCirculoResponse(AreaYPerimetro.area1.AreaCirculoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AreaCirculoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AreaCirculoResult;
        
        public AreaCirculoResponseBody() {
        }
        
        public AreaCirculoResponseBody(string AreaCirculoResult) {
            this.AreaCirculoResult = AreaCirculoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AreasPerimetrosSoapChannel : AreaYPerimetro.area1.AreasPerimetrosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AreasPerimetrosSoapClient : System.ServiceModel.ClientBase<AreaYPerimetro.area1.AreasPerimetrosSoap>, AreaYPerimetro.area1.AreasPerimetrosSoap {
        
        public AreasPerimetrosSoapClient() {
        }
        
        public AreasPerimetrosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AreasPerimetrosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreasPerimetrosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreasPerimetrosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AreaYPerimetro.area1.AreaTrianguloResponse AreaYPerimetro.area1.AreasPerimetrosSoap.AreaTriangulo(AreaYPerimetro.area1.AreaTrianguloRequest request) {
            return base.Channel.AreaTriangulo(request);
        }
        
        public string AreaTriangulo(double altura, double base1) {
            AreaYPerimetro.area1.AreaTrianguloRequest inValue = new AreaYPerimetro.area1.AreaTrianguloRequest();
            inValue.Body = new AreaYPerimetro.area1.AreaTrianguloRequestBody();
            inValue.Body.altura = altura;
            inValue.Body.base1 = base1;
            AreaYPerimetro.area1.AreaTrianguloResponse retVal = ((AreaYPerimetro.area1.AreasPerimetrosSoap)(this)).AreaTriangulo(inValue);
            return retVal.Body.AreaTrianguloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AreaYPerimetro.area1.AreaTrianguloResponse> AreaYPerimetro.area1.AreasPerimetrosSoap.AreaTrianguloAsync(AreaYPerimetro.area1.AreaTrianguloRequest request) {
            return base.Channel.AreaTrianguloAsync(request);
        }
        
        public System.Threading.Tasks.Task<AreaYPerimetro.area1.AreaTrianguloResponse> AreaTrianguloAsync(double altura, double base1) {
            AreaYPerimetro.area1.AreaTrianguloRequest inValue = new AreaYPerimetro.area1.AreaTrianguloRequest();
            inValue.Body = new AreaYPerimetro.area1.AreaTrianguloRequestBody();
            inValue.Body.altura = altura;
            inValue.Body.base1 = base1;
            return ((AreaYPerimetro.area1.AreasPerimetrosSoap)(this)).AreaTrianguloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AreaYPerimetro.area1.AreaCuadradoResponse AreaYPerimetro.area1.AreasPerimetrosSoap.AreaCuadrado(AreaYPerimetro.area1.AreaCuadradoRequest request) {
            return base.Channel.AreaCuadrado(request);
        }
        
        public string AreaCuadrado(double lado1, double lado2) {
            AreaYPerimetro.area1.AreaCuadradoRequest inValue = new AreaYPerimetro.area1.AreaCuadradoRequest();
            inValue.Body = new AreaYPerimetro.area1.AreaCuadradoRequestBody();
            inValue.Body.lado1 = lado1;
            inValue.Body.lado2 = lado2;
            AreaYPerimetro.area1.AreaCuadradoResponse retVal = ((AreaYPerimetro.area1.AreasPerimetrosSoap)(this)).AreaCuadrado(inValue);
            return retVal.Body.AreaCuadradoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AreaYPerimetro.area1.AreaCuadradoResponse> AreaYPerimetro.area1.AreasPerimetrosSoap.AreaCuadradoAsync(AreaYPerimetro.area1.AreaCuadradoRequest request) {
            return base.Channel.AreaCuadradoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AreaYPerimetro.area1.AreaCuadradoResponse> AreaCuadradoAsync(double lado1, double lado2) {
            AreaYPerimetro.area1.AreaCuadradoRequest inValue = new AreaYPerimetro.area1.AreaCuadradoRequest();
            inValue.Body = new AreaYPerimetro.area1.AreaCuadradoRequestBody();
            inValue.Body.lado1 = lado1;
            inValue.Body.lado2 = lado2;
            return ((AreaYPerimetro.area1.AreasPerimetrosSoap)(this)).AreaCuadradoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AreaYPerimetro.area1.AreaCirculoResponse AreaYPerimetro.area1.AreasPerimetrosSoap.AreaCirculo(AreaYPerimetro.area1.AreaCirculoRequest request) {
            return base.Channel.AreaCirculo(request);
        }
        
        public string AreaCirculo(double radio1) {
            AreaYPerimetro.area1.AreaCirculoRequest inValue = new AreaYPerimetro.area1.AreaCirculoRequest();
            inValue.Body = new AreaYPerimetro.area1.AreaCirculoRequestBody();
            inValue.Body.radio1 = radio1;
            AreaYPerimetro.area1.AreaCirculoResponse retVal = ((AreaYPerimetro.area1.AreasPerimetrosSoap)(this)).AreaCirculo(inValue);
            return retVal.Body.AreaCirculoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AreaYPerimetro.area1.AreaCirculoResponse> AreaYPerimetro.area1.AreasPerimetrosSoap.AreaCirculoAsync(AreaYPerimetro.area1.AreaCirculoRequest request) {
            return base.Channel.AreaCirculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AreaYPerimetro.area1.AreaCirculoResponse> AreaCirculoAsync(double radio1) {
            AreaYPerimetro.area1.AreaCirculoRequest inValue = new AreaYPerimetro.area1.AreaCirculoRequest();
            inValue.Body = new AreaYPerimetro.area1.AreaCirculoRequestBody();
            inValue.Body.radio1 = radio1;
            return ((AreaYPerimetro.area1.AreasPerimetrosSoap)(this)).AreaCirculoAsync(inValue);
        }
    }
}
